apiVersion: apps/v1                
kind: Deployment
metadata:
  name: task-a2
  labels:
    app: task-a2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-a2
  template:
    metadata:
      labels:
        app: task-a2
    spec:
      containers:
      - name: task-a2
        image: clikethis123/task-a2
        ports:
        - containerPort: 3000

